apiVersion: v1
kind: Secret
metadata:
  name: mrmahesh-cms-secret
  namespace: media
  labels:
    app: mrmahesh-cms
type: Opaque
stringData:
  JWT_SECRET: "mrmahesh_homelab_secure_jwt_secret_key_2026"
