apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mrmahesh-cms-db-pvc
  namespace: media
  labels:
    app: mrmahesh-cms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: network-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mrmahesh-cms-content-pvc
  namespace: media
  labels:
    app: mrmahesh-cms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: network-storage
  resources:
    requests:
      storage: 5Gi
